# Generated by Django 3.2.13 on 2023-09-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=50)),
                ('director', models.CharField(max_length=70)),
                ('mainProgrammer', models.CharField(max_length=70)),
                ('producer', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Mecanicas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=50)),
                ('discription', models.CharField(max_length=100)),
                ('howMuchILike', models.CharField(choices=[('S', 'Super Gosto'), ('M', 'Maneirinho'), ('N', 'Nhe')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=50)),
                ('releaseDate', models.DateField()),
                ('platforms', models.CharField(max_length=50)),
            ],
        ),
    ]
